name: zAntiDrop
version: 1.0.2
main: ovh.zeme.zantidrop.zAntiDrop
api-version: '1.16'
author: zeme
commands:
  antidrop:
    permission: zantidrop.admin
    usage: /antidrop <on|off>
permissions:
  zantidrop.admin:
    default: op
  zantidrop.dropitems:
    default: op
